on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: Get list of modified files
        id: modified-files
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { files } } = await github.rest.repos.getCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.sha
            });
            const fileNames = files.map(f => f.filename).join(' ');
            core.setOutput('files', fileNames);
      - name: Iterate and process each modified file via SSH
        run: |
          start_deploy="false"
          for file in ${{ steps.modified-files.outputs.files }}; do
              echo "Fue modificado $file"
              if [[ ! "$file" =~ ".yml" ]]; then
                  start_deploy="true"
              fi
          done
          echo "start_deploy<<EOF" >> $GITHUB_ENV
          echo "$start_deploy" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: executing remote ssh commands using ssh key
        if: env.start_deploy == 'true'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ssh -i ~/id_rsaalain mome@192.168.0.98 '
            cd galileo-newdev/${{ secrets.SERVICIO }}/galileo_servicio_web &&
            git fetch origin &&
            git reset --hard origin/main &&
            git pull &&
            cd ../../ &&
            CONTAINER_NAME="servicio-${{ secrets.SERVICIO }}" &&
            CN=$(docker ps -a --filter name="servicio-${{ secrets.SERVICIO }}" --format "{{.Names}}") &&
            if [[ -n "$CN" ]]; then
              echo "Dentro" &&
              IMAGE_NAME=$(docker inspect --format='{{.Config.Image}}' "$CONTAINER_NAME") &&
              if [[ -n "$IMAGE_NAME" ]]; then
                echo "Dentro" &&
                docker stop "$CONTAINER_NAME" &&
                docker rm "$CONTAINER_NAME" &&
                docker rmi "$IMAGE_NAME" &&
                echo "$IMAGE_NAME"
              fi
            fi &&
            docker compose up servicio-${{ secrets.SERVICIO }} -d &&
            yes | sudo docker builder prune'
            exit
