on:
  push:
    branches:
      - testCompilation
  workflow_dispatch:
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      # Checkout el código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Cambia a la versión que necesite tu proyecto
          cache: 'npm'

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Compilar la aplicación Angular
      - name: Build Angular app
        run: npm run build -- --configuration=production

      # 5. Comprimir la carpeta dist localmente
      - name: Compress dist folder
        run: tar -czvf dist.tar.gz dist/

      # 6. Transferir el archivo comprimido al servidor remoto usando appleboy/ssh-action
      - name: Transfer dist.tar.gz to remote server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}             # Cambia el puerto si es diferente
          source: "dist.tar.gz"                     # Archivo comprimido local
          target: "/home/countigo/dist_galileo"     # Ruta de destino en el servidor

      - name: executing remote ssh commands using ssh key
        #if: env.start_deploy == 'true'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ls &&
            scp -i ~/id_rsaalain /home/countigo/dist_galileo/dist.tar.gz mome@192.168.0.212:/home/mome/galileo-dev-v1.1/webapp &&
            ssh -i ~/id_rsaalain mome@192.168.0.212 '
            set -e &&
            tar -xzvf /home/mome/galileo-dev-v1.1/webapp/dist.tar.gz -C /home/mome/galileo-dev-v1.1/webapp &&
            rm /home/mome/galileo-dev-v1.1/webapp/dist.tar.gz'
            exit
